### ISSUE TITLE
https://github.com hangs up in an ugly way if there is no Host: header

### ISSUE THREAD

**Issue by aantron** [aantron/hyper#3]
...or else Hyper interprets the response in an ugly way. In any case, Hyper's higher-level helpers should add the header and/or Hyper should document that the header might be required by servers.

**Comment by andreypopp** [comment]
Curl sets the following headers by default:

```
; curl 'http://github.com/' -v
*   Trying 140.82.121.4:80...
* Connected to github.com (140.82.121.4) port 80 (#0)
> GET / HTTP/1.1
> Host: github.com
> User-Agent: curl/7.74.0
> Accept: */*
```

**Comment by tmattio** [comment]
I've hit this when querying https://watch.ocaml.org/ as well.
